  app:
          db_name:  "zeus"
          db_port: "5432"
          db_host: "172.26.5.38"
          db_username: "jointree"
          db_password: "jointree123"
  
keycloak:
  userEndpoint: "https://docker.jointree.co.kr:8443/auth/admin/realms/parthenon/users"
  groupEndpoint: "https://docker.jointree.co.kr:8443/auth/admin/realms/parthenon/groups"

     
       

